set(SOURCES ${SOURCES}
    src/ActionGenerator.cpp
    src/ActionGenerator.h
    src/DiscoveryMusicManager.cpp
    src/DiscoveryMusicManager.h
    src/FormUtil.cpp
    src/FormUtil.h
    src/GFxUtil.cpp
    src/GFxUtil.h
    src/Hooks.cpp
    src/Hooks.h
    src/ImportData.cpp
    src/ImportData.h
    src/ImportManager.cpp
    src/ImportManager.h
    src/MapConfigLoader.cpp
    src/MapConfigLoader.h
    src/PCH.cpp
    src/PCH.h
    src/SWFOutputStream.cpp
    src/SWFOutputStream.h
    src/Settings.cpp
    src/Settings.h
    src/TagFactory.cpp
    src/TagFactory.h
    src/main.cpp
)
