set(SOURCES ${SOURCES}
    src/PCH/PCH.cpp
    src/PCH/PCH.h
    src/RE/Ext.h
    src/RE/G/GASActionBufferData.h
    src/RE/G/GASDoAction.h
    src/RE/G/GASExecuteTag.h
    src/RE/G/GAcquireInterface.h
    src/RE/G/GArrayConstPolicy.h
    src/RE/G/GEvent.h
    src/RE/G/GFxCharacterDef.h
    src/RE/G/GFxInitImportActions.h
    src/RE/G/GFxLoadUpdateSync.h
    src/RE/G/GFxMovieDataDef.h
    src/RE/G/GFxMovieDefBindStates.h
    src/RE/G/GFxMovieDefImpl.h
    src/RE/G/GFxPlaceObject.h
    src/RE/G/GFxPlaceObject2.h
    src/RE/G/GFxPlaceObject2a.h
    src/RE/G/GFxPlaceObject3.h
    src/RE/G/GFxPlaceObjectBase.h
    src/RE/G/GFxPlaceObjectUnpacked.h
    src/RE/G/GFxRemoveObject.h
    src/RE/G/GFxRemoveObject2.h
    src/RE/G/GFxResourceLib.h
    src/RE/G/GFxResourceReport.h
    src/RE/G/GFxSpriteDef.h
    src/RE/G/GFxStateBagImpl.h
    src/RE/G/GFxTimelineDef.h
    src/RE/G/GHashUncached.h
    src/RE/G/GHashsetNodeEntry.h
    src/RE/G/GMutex.h
    src/RE/G/GWaitCondition.h
    src/RE/G/GWaitable.h
    src/RE/OffsetsExt.h
    src/RE/S/SpecialMarkerData.h
    src/REL/Pattern.h
    src/SWF/ActionGenerator.cpp
    src/SWF/ActionGenerator.h
    src/SWF/SWFOutputStream.cpp
    src/SWF/SWFOutputStream.h
    src/SWF/TagFactory.cpp
    src/SWF/TagFactory.h
    src/Util/FormUtil.cpp
    src/Util/FormUtil.h
    src/Util/GFxUtil.cpp
    src/Util/GFxUtil.h
    src/Util/MapMarkerUtil.cpp
    src/Util/MapMarkerUtil.h
    src/main/DiscoveryMusicManager.cpp
    src/main/DiscoveryMusicManager.h
    src/main/ImportData.cpp
    src/main/ImportData.h
    src/main/ImportManager.cpp
    src/main/ImportManager.h
    src/main/LocalMapManager.cpp
    src/main/LocalMapManager.h
    src/main/MapConfigLoader.cpp
    src/main/MapConfigLoader.h
    src/main/Patch.cpp
    src/main/Patch.h
    src/main/SKSEPlugin.cpp
    src/main/Settings.cpp
    src/main/Settings.h
)
